# Generated by Django 2.2.16 on 2023-02-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230206_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Запретное слово')),
            ],
            options={
                'verbose_name': 'Запретное слово',
                'verbose_name_plural': 'Запретные слова',
                'ordering': ('word',),
            },
        ),
    ]
